from StartPage import *
from HomePaz import *
from InserisciDatiGiornalieri import *
from VisPaz import *
from ModPaz import *
from HomeMed import *
from HomeResp import *
from AddUtente import *
from ShowTerapie import *
from DatiPersonali import *